---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  attributes:
    java:
      ark_retries: 2
      ark_retry_delay: 10

platforms:
  - name: ubuntu-18.04
    box: ubuntu-18.04
    box_url: ../bento/builds/ubuntu-18.04.virtualbox.box
  - name: debian-8.7
    box: debian-8.7
    box_url: ../bento/builds/debian-8.7.virtualbox.box
  - name: centos-6.9
    box: centos-6.9
    box_url: ../bento/builds/centos-6.9.virtualbox.box
  - name: centos-7.4
    box: centos-7.4
    box_url: ../bento/builds/centos-7.4.virtualbox.box

suites:
  - name: default
    run_list:
      - recipe[artifactory::default]
    attributes:
      java:
        oracle:
          accept_oracle_download_terms: true
        install_flavor: oracle
